# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

function Update-RepoDigest {
    <#
    .SYNOPSIS
        Generate or refresh .ai/repo-map.md from `git ls-files`.

    .DESCRIPTION
        Top-level paths + file-extension counts + (optionally) entrypoints. Cheap and
        deterministic — safe to run on every loop tick.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [string] $Path = (Get-Location).ProviderPath,
        [string] $OutFile
    )

    $root = $null
    try { $root = (& git -C $Path rev-parse --show-toplevel 2>$null).Trim() } catch { }
    if (-not $root) { throw "Update-RepoDigest: $Path is not in a git working tree." }

    $files = @(& git -C $root ls-files 2>$null)
    $top = $files | ForEach-Object { ($_ -split '/')[0] } | Sort-Object -Unique
    $extCounts = $files |
        Group-Object { [System.IO.Path]::GetExtension($_) } |
        Sort-Object Count -Descending |
        Select-Object -First 30

    $markerStart = '<!-- wizard-managed-block:start -->'
    $markerEnd   = '<!-- wizard-managed-block:end -->'

    $managedLines = @()
    $managedLines += $markerStart
    $managedLines += '# Repo map'
    $managedLines += ''
    $managedLines += "Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz')"
    $managedLines += "Root: $root"
    $managedLines += ''
    $managedLines += '## Top-level paths'
    foreach ($t in $top) { $managedLines += "- ``$t``" }
    $managedLines += ''
    $managedLines += '## File extensions (top 30 by count)'
    foreach ($g in $extCounts) {
        $name = if ($g.Name) { $g.Name } else { '(no-ext)' }
        $managedLines += "- ``$name``: $($g.Count)"
    }
    $managedLines += ''
    $managedLines += '## Notes'
    $managedLines += '- Generated by `Update-RepoDigest`. Content **outside** the wizard-managed-block markers (start/end HTML comments) is preserved across regeneration. Content inside is overwritten on every run.'
    $managedLines += $markerEnd

    if (-not $OutFile) {
        $aiDir = Join-Path $root '.ai'
        if (-not (Test-Path -LiteralPath $aiDir)) { New-Item -ItemType Directory -Force -Path $aiDir | Out-Null }
        $OutFile = Join-Path $aiDir 'repo-map.md'
    }

    $managedBlock = $managedLines -join "`n"

    if (Test-Path -LiteralPath $OutFile) {
        $existing = Get-Content -LiteralPath $OutFile -Raw -Encoding utf8
        $startIdx = $existing.IndexOf($markerStart)
        $endIdx = $existing.IndexOf($markerEnd, [Math]::Max(0, $startIdx))
        if ($startIdx -ge 0 -and $endIdx -gt $startIdx) {
            $newContent = $existing.Substring(0, $startIdx) + $managedBlock + $existing.Substring($endIdx + $markerEnd.Length)
            $newContent | Set-Content -LiteralPath $OutFile -Encoding utf8 -NoNewline
        } else {
            # Existing file has no marker — preserve what's there by appending the managed block,
            # separated by a blank line. The user can move it around manually if they prefer.
            ($existing.TrimEnd() + "`n`n" + $managedBlock + "`n") | Set-Content -LiteralPath $OutFile -Encoding utf8 -NoNewline
        }
    } else {
        ($managedBlock + "`n") | Set-Content -LiteralPath $OutFile -Encoding utf8 -NoNewline
    }

    [pscustomobject]@{
        PSTypeName  = 'WizardRepoDigest'
        Root        = $root
        OutFile     = $OutFile
        FileCount   = $files.Count
        TopLevel    = @($top)
        Extensions  = ($extCounts | ForEach-Object { @{ ext = $_.Name; count = $_.Count } })
    }
}
