# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

function Update-RepoDigest {
    <#
    .SYNOPSIS
        Generate or refresh .ai/repo-map.md from `git ls-files`.

    .DESCRIPTION
        Top-level paths + file-extension counts + (optionally) entrypoints. Cheap and
        deterministic — safe to run on every loop tick.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [string] $Path = (Get-Location).ProviderPath,
        [string] $OutFile
    )

    $root = $null
    try { $root = (& git -C $Path rev-parse --show-toplevel 2>$null).Trim() } catch { }
    if (-not $root) { throw "Update-RepoDigest: $Path is not in a git working tree." }

    $files = @(& git -C $root ls-files 2>$null)
    $top = $files | ForEach-Object { ($_ -split '/')[0] } | Sort-Object -Unique
    $extCounts = $files |
        Group-Object { [System.IO.Path]::GetExtension($_) } |
        Sort-Object Count -Descending |
        Select-Object -First 30

    $lines = @()
    $lines += '# Repo map'
    $lines += ''
    $lines += "Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz')"
    $lines += "Root: $root"
    $lines += ''
    $lines += '## Top-level paths'
    foreach ($t in $top) { $lines += "- ``$t``" }
    $lines += ''
    $lines += '## File extensions (top 30 by count)'
    foreach ($g in $extCounts) {
        $name = if ($g.Name) { $g.Name } else { '(no-ext)' }
        $lines += "- ``$name``: $($g.Count)"
    }
    $lines += ''
    $lines += '## Notes'
    $lines += '- Generated by `Update-RepoDigest`. Edit by hand if you need to add curated guidance — additions outside the auto-generated sections will be preserved on regeneration in a future update.'

    if (-not $OutFile) {
        $aiDir = Join-Path $root '.ai'
        if (-not (Test-Path -LiteralPath $aiDir)) { New-Item -ItemType Directory -Force -Path $aiDir | Out-Null }
        $OutFile = Join-Path $aiDir 'repo-map.md'
    }

    $lines -join "`n" | Set-Content -LiteralPath $OutFile -Encoding utf8

    [pscustomobject]@{
        PSTypeName  = 'WizardRepoDigest'
        Root        = $root
        OutFile     = $OutFile
        FileCount   = $files.Count
        TopLevel    = @($top)
        Extensions  = ($extCounts | ForEach-Object { @{ ext = $_.Name; count = $_.Count } })
    }
}
